apiVersion: v1
kind: Service
metadata:
  name: servicemesh-nginx
  labels:
    app: servicemesh-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: servicemesh-nginx