apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemesh-flask-v1
spec:
  selector:
    matchLabels:
      app: servicemesh-flask
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: servicemesh-flask
        version: v1
    spec:
      containers:
        - image: docker.io/jaipalkomakula/flask:v1
          name: flask-v1
          ports:
          - containerPort: 5000