apiVersion: v1
kind: Service
metadata:
  name: servicemesh-flask
  labels:
    app: servicemesh-flask
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: servicemesh-flask